const COUNTRY_FLAGS: { [key: string]: string } = {
    // Europe
    "Germany": "🇩🇪",
    "France": "🇫🇷",
    "United Kingdom": "🇬🇧",
    "Italy": "🇮🇹",
    "Spain": "🇪🇸",
    "Poland": "🇵🇱",
    "Ukraine": "🇺🇦",
    "Romania": "🇷🇴",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Czech Republic": "🇨🇿",
    "Greece": "🇬🇷",
    "Portugal": "🇵🇹",
    "Sweden": "🇸🇪",
    "Hungary": "🇭🇺",
    "Austria": "🇦🇹",
    "Switzerland": "🇨🇭",
    "Bulgaria": "🇧🇬",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Slovakia": "🇸🇰",
    "Norway": "🇳🇴",
    "Ireland": "🇮🇪",
    "Croatia": "🇭🇷",
    "Moldova": "🇲🇩",
    "Bosnia and Herzegovina": "🇧🇦",
    "Albania": "🇦🇱",
    "Lithuania": "🇱🇹",
    "North Macedonia": "🇲🇰",
    "Slovenia": "🇸🇮",
    "Latvia": "🇱🇻",
    "Estonia": "🇪🇪",
    "Montenegro": "🇲🇪",
    "Luxembourg": "🇱🇺",
    "Malta": "🇲🇹",
    "Iceland": "🇮🇸",
    "Andorra": "🇦🇩",
    "Monaco": "🇲🇨",
    "Liechtenstein": "🇱🇮",
    "San Marino": "🇸🇲",
    "Vatican City": "🇻🇦",

    // Asia
    "China": "🇨🇳",
    "India": "🇮🇳",
    "Japan": "🇯🇵",
    "South Korea": "🇰🇷",
    "Indonesia": "🇮🇩",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Malaysia": "🇲🇾",
    "Philippines": "🇵🇭",
    "Singapore": "🇸🇬",
    "Myanmar": "🇲🇲",
    "Cambodia": "🇰🇭",
    "Laos": "🇱🇦",
    "Brunei": "🇧🇳",
    "East Timor": "🇹🇱",
    "Mongolia": "🇲🇳",
    "Nepal": "🇳🇵",
    "Bhutan": "🇧🇹",
    "Bangladesh": "🇧🇩",
    "Sri Lanka": "🇱🇰",
    "Maldives": "🇲🇻",
    "Pakistan": "🇵🇰",
    "Afghanistan": "🇦🇫",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Saudi Arabia": "🇸🇦",
    "Yemen": "🇾🇪",
    "Oman": "🇴🇲",
    "United Arab Emirates": "🇦🇪",
    "Qatar": "🇶🇦",
    "Kuwait": "🇰🇼",
    "Bahrain": "🇧🇭",
    "Jordan": "🇯🇴",
    "Lebanon": "🇱🇧",
    "Syria": "🇸🇾",
    "Israel": "🇮🇱",
    "Palestine": "🇵🇸",
    "Cyprus": "🇨🇾",
    "Turkey": "🇹🇷",
    "Georgia": "🇬🇪",
    "Armenia": "🇦🇲",
    "Azerbaijan": "🇦🇿",
    "Kazakhstan": "🇰🇿",
    "Uzbekistan": "🇺🇿",
    "Turkmenistan": "🇹🇲",
    "Kyrgyzstan": "🇰🇬",
    "Tajikistan": "🇹🇯",

    // Africa
    "Nigeria": "🇳🇬",
    "Ethiopia": "🇪🇹",
    "Egypt": "🇪🇬",
    "Democratic Republic of the Congo": "🇨🇩",
    "Tanzania": "🇹🇿",
    "South Africa": "🇿🇦",
    "Kenya": "🇰🇪",
    "Uganda": "🇺🇬",
    "Sudan": "🇸🇩",
    "Algeria": "🇩🇿",
    "Morocco": "🇲🇦",
    "Angola": "🇦🇴",
    "Ghana": "🇬🇭",
    "Mozambique": "🇲🇿",
    "Madagascar": "🇲🇬",
    "Cameroon": "🇨🇲",
    "Côte d'Ivoire": "🇨🇮",
    "Niger": "🇳🇪",
    "Burkina Faso": "🇧🇫",
    "Mali": "🇲🇱",
    "Malawi": "🇲🇼",
    "Zambia": "🇿🇲",
    "Senegal": "🇸🇳",
    "Chad": "🇹🇩",
    "Somalia": "🇸🇴",
    "Zimbabwe": "🇿🇼",
    "Guinea": "🇬🇳",
    "Rwanda": "🇷🇼",
    "Benin": "🇧🇯",
    "Burundi": "🇧🇮",
    "Tunisia": "🇹🇳",
    "South Sudan": "🇸🇸",
    "Togo": "🇹🇬",
    "Sierra Leone": "🇸🇱",
    "Libya": "🇱🇾",
    "Congo": "🇨🇬",
    "Liberia": "🇱🇷",
    "Central African Republic": "🇨🇫",
    "Mauritania": "🇲🇷",
    "Eritrea": "🇪🇷",
    "Namibia": "🇳🇦",
    "Gambia": "🇬🇲",
    "Botswana": "🇧🇼",
    "Gabon": "🇬🇦",
    "Lesotho": "🇱🇸",
    "Guinea-Bissau": "🇬🇼",
    "Equatorial Guinea": "🇬🇶",
    "Mauritius": "🇲🇺",
    "Eswatini": "🇸🇿",
    "Djibouti": "🇩🇯",
    "Comoros": "🇰🇲",
    "Cape Verde": "🇨🇻",
    "São Tomé and Príncipe": "🇸🇹",
    "Seychelles": "🇸🇨",

    // Oceania
    "Australia": "🇦🇺",
    "Papua New Guinea": "🇵🇬",
    "New Zealand": "🇳🇿",
    "Fiji": "🇫🇯",
    "Solomon Islands": "🇸🇧",
    "Vanuatu": "🇻🇺",
    "New Caledonia": "🇳🇨",
    "French Polynesia": "🇵🇫",
    "Samoa": "🇼🇸",
    "Guam": "🇬🇺",
    "Kiribati": "🇰🇮",
    "Micronesia": "🇫🇲",
    "Tonga": "🇹🇴",
    "Marshall Islands": "🇲🇭",
    "Northern Mariana Islands": "🇲🇵",
    "American Samoa": "🇦🇸",
    "Palau": "🇵🇼",
    "Cook Islands": "🇨🇰",
    "Tuvalu": "🇹🇻",
    "Nauru": "🇳🇷",
    "Niue": "🇳🇺",
    "Tokelau": "🇹🇰",
    "Wallis and Futuna": "🇼🇫",
    "Pitcairn Islands": "🇵🇳",

    // North America
    "United States": "🇺🇸",
    "Canada": "🇨🇦",
    "Greenland": "🇬🇱",
    "Cuba": "🇨🇺",
    "Haiti": "🇭🇹",
    "Dominican Republic": "🇩🇴",
    "Jamaica": "🇯🇲",
    "Trinidad and Tobago": "🇹🇹",
    "Bahamas": "🇧🇸",
    "Barbados": "🇧🇧",
    "Saint Lucia": "🇱🇨",
    "Grenada": "🇬🇩",
    "Saint Vincent and the Grenadines": "🇻🇨",
    "Antigua and Barbuda": "🇦🇬",
    "Dominica": "🇩🇲",
    "Saint Kitts and Nevis": "🇰🇳",
    "Panama": "🇵🇦",
    "Costa Rica": "🇨🇷",
    "Nicaragua": "🇳🇮",
    "Honduras": "🇭🇳",
    "El Salvador": "🇸🇻",
    "Guatemala": "🇬🇹",
    "Belize": "🇧🇿",

    // South America
    "Mexico": "🇲🇽",
    "Brazil": "🇧🇷",
    "Argentina": "🇦🇷",
    "Chile": "🇨🇱",
    "Colombia": "🇨🇴",
    "Peru": "🇵🇪",
    "Venezuela": "🇻🇪",
    "Ecuador": "🇪🇨",
    "Bolivia": "🇧🇴",
    "Paraguay": "🇵🇾",
    "Uruguay": "🇺🇾",
    "Guyana": "🇬🇾",
    "Suriname": "🇸🇷",
    "French Guiana": "🇬🇫",
};

// Helper function to get country flag
export function getCountryFlag(countryName: string): string {
    return COUNTRY_FLAGS[countryName] || "🏳️";
}
