# Generated by Django 4.2.20 on 2025-06-15 18:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(help_text='The domain of the website to track', max_length=255)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The API key which is used to authenticate requests')),
                ('geolocation_api_token_ipinfo', models.CharField(help_text='The access token to the IPInfo API', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who created the domain', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_visitor_geolocator_core_domain',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_description', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=510)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_visitor_geolocator_core.domain')),
            ],
            options={
                'db_table': 'website_visitor_geolocator_core_visitor',
            },
        ),
    ]
