# Generated by Django 4.2.20 on 2025-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website_visitor_geolocator_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created the domain",
                on_delete=django.db.models.deletion.CASCADE,
                to="website_visitor_geolocator_core.websitevisitorgeolocatoruser",
            ),
        ),
    ]
