# Generated by Django 4.2.20 on 2025-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_visitor_geolocator_core", "0002_alter_domain_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
