# Generated by Django 4.2.20 on 2025-06-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_visitor_geolocator_core", "0003_domain_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="geolocation_api_token_ipinfo",
            field=models.CharField(
                blank=True,
                help_text="The access token to the IPInfo API",
                max_length=255,
                null=True,
            ),
        ),
    ]
