# Generated by Django 4.2.16 on 2025-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website_visitor_geolocator_core",
            "0004_alter_domain_geolocation_api_token_ipinfo",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteVisitorGeolocatorPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "website_visitor_geolocator_enabled",
                        "Is the website visitor geolocator enabled for the user",
                    )
                ],
            },
        ),
    ]
