# Generated by Django 4.2.16 on 2026-03-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_visitor_geolocator_core", "0005_websitevisitorgeolocatorpermissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="user_agent_parsed",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
