# Generated by Django 4.2.20 on 2025-06-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("website_visitor_geolocator_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website_visitor_geolocator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website_visitor_geolocator_core.websitevisitorgeolocatoruser",
                    ),
                ),
            ],
            options={
                "db_table": "website_visitor_geolocator_push_subscription",
            },
        ),
    ]
