# Generated by Django 4.2.20 on 2025-06-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "website_visitor_geolocator_core",
            "0004_alter_domain_geolocation_api_token_ipinfo",
        ),
        ("website_visitor_geolocator_notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_chance",
                    models.IntegerField(
                        default=100,
                        help_text="Chance of receiving website_visitor_geolocator_notifications (0-100)",
                    ),
                ),
                (
                    "new_visitor_website_visitor_geolocator_notifications",
                    models.BooleanField(default=True),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("notification_vibration", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website_visitor_geolocator_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="website_visitor_geolocator_core.websitevisitorgeolocatoruser",
                    ),
                ),
            ],
            options={
                "db_table": "website_visitor_geolocator_notification_preferences",
            },
        ),
    ]
