# Generated by Django 4.2.20 on 2025-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="daily_summary_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationpreferences",
            name="weekly_summary_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
