# Generated by Django 4.2.16 on 2025-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website_visitor_geolocator_notifications",
            "0003_notificationpreferences_daily_summary_notifications_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationpreferences",
            old_name="daily_summary_website_visitor_geolocator_notifications",
            new_name="daily_summary_notifications",
        ),
        migrations.RenameField(
            model_name="notificationpreferences",
            old_name="new_visitor_website_visitor_geolocator_notifications",
            new_name="new_visitor_notifications",
        ),
        migrations.RenameField(
            model_name="notificationpreferences",
            old_name="weekly_summary_website_visitor_geolocator_notifications",
            new_name="weekly_summary_notifications",
        ),
        migrations.AlterField(
            model_name="notificationpreferences",
            name="notification_chance",
            field=models.IntegerField(
                default=100, help_text="Chance of receiving notifications (0-100)"
            ),
        ),
    ]
