# Generated by Django 4.2.20 on 2025-07-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website_visitor_geolocator_notifications",
            "0004_rename_daily_summary_website_visitor_geolocator_notifications_notificationpreferences_daily_summary_",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PushSubscription",
        ),
    ]
