# Generated by Django 4.2.16 on 2026-03-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website_visitor_geolocator_core", "0005_websitevisitorgeolocatorpermissions"),
        ("website_visitor_geolocator_notifications", "0005_delete_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_visitor_notifications", models.BooleanField(default=True)),
                ("daily_summary_notifications", models.BooleanField(default=False)),
                ("weekly_summary_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website_visitor_geolocator_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_notification_preferences",
                        to="website_visitor_geolocator_core.websitevisitorgeolocatoruser",
                    ),
                ),
            ],
            options={
                "db_table": "website_visitor_geolocator_summary_notification_preferences",
            },
        ),
        migrations.DeleteModel(
            name="NotificationPreferences",
        ),
    ]
